language: rust
rust:
  - nightly
  - beta
  - stable
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
deploy:
  provider: script
  script:
    - cargo login $CARGO_TOKEN && cargo package && cargo publish
  on:
    tags: true
